# Generated by Django 4.2.1 on 2024-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC_Primary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_license', models.ImageField(blank=True, null=True, upload_to='docs/user-uploads/drivers_license/')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='docs/user-uploads/passport/')),
                ('govt_photo_id', models.ImageField(blank=True, null=True, upload_to='docs/user-uploads/govt_photo_id/')),
                ('us_armed_forces_id', models.ImageField(blank=True, null=True, upload_to='docs/user-uploads/us_armed_forces_id/')),
                ('us_alien_registration_card', models.ImageField(blank=True, null=True, upload_to='docs/user-uploads/us_alien_registration_card/')),
                ('permanent_resident_card', models.ImageField(blank=True, null=True, upload_to='docs/user-uploads/permanent_resident_card/')),
            ],
        ),
    ]
