# Generated by Django 4.2.1 on 2024-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_primary',
            name='drivers_license',
            field=models.ImageField(blank=True, null=True, upload_to='docs/drivers_license/'),
        ),
        migrations.AlterField(
            model_name='kyc_primary',
            name='govt_photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='docs/govt_photo_id/'),
        ),
        migrations.AlterField(
            model_name='kyc_primary',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='docs/passport/'),
        ),
        migrations.AlterField(
            model_name='kyc_primary',
            name='permanent_resident_card',
            field=models.ImageField(blank=True, null=True, upload_to='docs/permanent_resident_card/'),
        ),
        migrations.AlterField(
            model_name='kyc_primary',
            name='us_alien_registration_card',
            field=models.ImageField(blank=True, null=True, upload_to='docs/us_alien_registration_card/'),
        ),
        migrations.AlterField(
            model_name='kyc_primary',
            name='us_armed_forces_id',
            field=models.ImageField(blank=True, null=True, upload_to='docs/us_armed_forces_id/'),
        ),
    ]
