# Generated by Django 4.2.1 on 2024-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_kyc_primary_drivers_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_primary',
            name='document_type',
            field=models.CharField(choices=[('drivers_license', "Driver's License"), ('passport', 'Passport'), ('govt_photo_id', 'Government Photo ID'), ('us_armed_forces_id', 'U.S Armed Forces ID'), ('us_alien_registration_card', 'U.S Alien Registration Card'), ('permanent_resident_card', 'Permanent Resident Card')], default='drivers_license', max_length=100),
        ),
    ]
