# Generated by Django 4.2.1 on 2024-05-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_kyc_primary_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc_primary',
            name='drivers_license',
        ),
        migrations.RemoveField(
            model_name='kyc_primary',
            name='govt_photo_id',
        ),
        migrations.RemoveField(
            model_name='kyc_primary',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='kyc_primary',
            name='permanent_resident_card',
        ),
        migrations.RemoveField(
            model_name='kyc_primary',
            name='us_alien_registration_card',
        ),
        migrations.RemoveField(
            model_name='kyc_primary',
            name='us_armed_forces_id',
        ),
        migrations.AddField(
            model_name='kyc_primary',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
