# Generated by Django 5.0.6 on 2024-05-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_remove_kyc_primary_drivers_license_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDocumentaryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='non_documentary_verification/')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='primary_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='secondary_documents/')),
            ],
        ),
    ]
