# Generated by Django 5.0.4 on 2024-06-04 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_nondocumentaryverification_primarydocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='new_application_documents/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
